# Generated by Django 5.2.7 on 2025-10-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_inscripcion_curso_estudiantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
