# Generated by Django 5.2.6 on 2025-10-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('ver_posts_exclusivos', 'Ver publicaciones exclusivas')]},
        ),
    ]
