# Generated by Django 5.2.7 on 2025-10-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triciclos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=30)),
                ('triciclo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='triciclos.triciclo')),
            ],
        ),
    ]
