# Generated by Django 5.2.7 on 2025-10-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triciclos', '0002_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='triciclo',
            name='anio',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
