# Generated by Django 5.2.7 on 2025-10-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triciclos', '0003_triciclo_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='triciclo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='triciclo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
